server:
  port: 9091

eureka:
  instance:
    hostname: http://registry.platform.svc.cluster.local
    nonSecurePort: 7777
    preferIpAddress: false
  client:
    serviceUrl:
      defaultZone: http://registry.platform.svc.cluster.local:8080/eureka/

spring:
  application:
    name: identity-integration-service
  profiles:
    active: ${DBS_ACTIVE_PROFILE:live}

idempotencyConfiguration:
  cacheName: identity-integration-serviceCache

backbase:
  web:
    security:
      enabled: true
  security:
    mtls:
      enabled: false

identity:
  serverUrl: http://localhost:8180/auth
  masterAdmin:
    realmName: master
    username: admin
    password: admin
    clientId: admin-cli
  enableUser: true